return {
    {
        key = game,
        lookup = {
            "Workspace",
            "SoundService",
            "Chat",
            "Players",
            "ReplicatedFirst",
            "MaterialService",
            "TextChatService",
            "StarterPlayer",
            "StarterPack",
            "StarterGui",
            "CoreGui",
            "LocalizationService",
            "VRService",
            "PublishService",
            "ReplicatedStorage",
            "ServerScriptService",
            "ServerStorage",
            "PathfindingService",
            "PluginGuiService",
            "HapticService",
            "Lighting",
            "Teams",
            "TestService",
            "VoiceChatService",
            "TextBoxService",
            "UGCValidationService"
        }
    },
    {
        key = "nil",
        -- lookup = getnilinstances,
        -- lookupDelay = 1
    }
}
